export const SUCCESS_CODE = 0;
export const shareObj = {
  code: '', // 代码
  name: '', // 名称
  status: '', // 状态
  market: '', // 市场
  date: '', // 日期
  timeStamp: '', // 时间戳
  sellFivePrice: '', // 卖五价格
  sellFourPrice: '', // 卖四价格
  sellThreePrice: '', // 卖三价格
  sellTwoPrice: '', // 卖二价格
  sellOnePrice: '', // 卖一价格
  sellFiveCounts: '', // 卖五手数
  sellFourCounts: '', // 卖四手数
  sellThreeCounts: '', // 卖三手数
  sellTwoCounts: '', // 卖二手数
  sellOneCounts: '', // 卖一手数
  buyOnePrice: '', // 买一价格
  buyTwoPrice: '', // 买二价格
  buyThreePrice: '', // 买三价格
  buyFourPrice: '', // 买四价格
  buyFivePrice: '', // 买五价格
  buyOneCounts: '', // 买一手数
  buyTwoCounts: '', // 买二手数
  buyThreeCounts: '', // 买三手数
  buyFourCounts: '', // 买四手数
  buyFiveCounts: '', // 买五手数
  closePrice: '', // 昨收
  openPrice: '', // 今开
  highest: '', // 最高
  lowest: '', // 最低
  newest: '', // 最新价
  dealCounts: '', // 成交量
  dealMoney: '', // 成交额
  outside: '', // 外盘
  inside: '', // 内盘
  upDownMoney: '', // 涨跌额
  upDownApr: '', // 涨跌率
  lastDealCount: '', // 成交量（收盘最后一笔）
  lmr: '', // 量比
  ttm: '', // 市盈率
  en: '', // 英文缩写
};
